In [2]:
####3.变换，transform修改特征、target_transform修改标签
import torch
from torchvision import datasets
from torchvision.transforms import ToTensor, Lambda
#特征转为张量，标签转为独热编码张量
ds = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
    #将PIL图像或ndarray的NumPy数组转换成Float张量，缩放图像的像素强度值在[0,1]
    target_transform=Lambda(lambda y: torch.zeros(10, dtype=torch.float).scatter_(0, torch.tensor(y), value=1))
    #创建一个size为10（标签数量）的零张量，调用scatter_ 通过标签y对应的索引值给对应的零张量位置上的值附上value 1.
)
for i in range(1, 10):
    sample_idx = torch.randint(len(ds), size=(1,)).item() #随机取出一张图片，并获得图片id
    img, label = ds[sample_idx]
    print(label)

tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.])
tensor([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])
tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])
tensor([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])
tensor([0., 1., 0., 0., 0., 0., 0., 0., 0., 0.])
